# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: movie.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmovie.proto\"\x1a\n\x07Message\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x15\n\x07MovieID\x12\n\n\x02id\x18\x01 \x01(\t\"/\n\x08\x44irector\x12\x11\n\tfirstName\x18\x01 \x01(\t\x12\x10\n\x08lastName\x18\x02 \x01(\t\"\xae\x01\n\tMovieData\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04rank\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x11\n\tfullTitle\x18\x04 \x01(\t\x12\x0c\n\x04year\x18\x05 \x01(\t\x12\r\n\x05image\x18\x06 \x01(\t\x12\x12\n\nimDbRating\x18\x07 \x01(\t\x12\x17\n\x0fimDbRatingCount\x18\x08 \x01(\t\x12\x1b\n\x08\x64irector\x18\t \x01(\x0b\x32\t.Director\",\n\x0eMovieDataArray\x12\x1a\n\x06movies\x18\x01 \x03(\x0b\x32\n.MovieData\"\x07\n\x05\x45mpty2\x9e\x01\n\x05Movie\x12\x1a\n\x04Home\x12\x06.Empty\x1a\x08.Message\"\x00\x12&\n\x0cGetMovieByID\x12\x08.MovieID\x1a\n.MovieData\"\x00\x12*\n\rGetListMovies\x12\x06.Empty\x1a\x0f.MovieDataArray\"\x00\x12%\n\x0b\x43reateMovie\x12\n.MovieData\x1a\x08.Message\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'movie_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=15
  _MESSAGE._serialized_end=41
  _MOVIEID._serialized_start=43
  _MOVIEID._serialized_end=64
  _DIRECTOR._serialized_start=66
  _DIRECTOR._serialized_end=113
  _MOVIEDATA._serialized_start=116
  _MOVIEDATA._serialized_end=290
  _MOVIEDATAARRAY._serialized_start=292
  _MOVIEDATAARRAY._serialized_end=336
  _EMPTY._serialized_start=338
  _EMPTY._serialized_end=345
  _MOVIE._serialized_start=348
  _MOVIE._serialized_end=506
# @@protoc_insertion_point(module_scope)
